kube-prometheus-stack:
  kubeControllerManager:
    enabled: true
  kubeScheduler:
    enabled: true
  prometheusOperator:
    admissionWebhooks:
      enabled: false
  prometheus:
    prometheusSpec:
      image:
        tag: v3.3.0-rc.1
